update Check_Input_Files.yml

diff --git a/.github/workflows/Check_Input_Files.yml b/.github/workflows/Check_Input_Files.yml
--- a/.github/workflows/Check_Input_Files.yml
+++ b/.github/workflows/Check_Input_Files.yml
@@ -26,24 +26,26 @@ jobs:
       qualification-plan: 'Evaluation/Input/evaluation_plan.json'
 
   test-check-bom:
-    run: |
-      shopt -s globstar
-      shopt -s nocaseglob
-      bom_found=false
-      for file in **/*.csv **/*.json **/*.md; do
-        if [ -f "$file" ]; then
-          bom=$(hexdump -n 3 -e '/1 "%02x"' "$file")
-          if [ "$bom" = "efbbbf" ]; then
-            echo "Error: File $file has a BOM"
-            echo "::error file=$file::File has BOM"
-            bom_found=true
-          else
-            echo "File $file is valid"
+    steps:
+      - name: Test Check for BOM in CSV, JSON and MD files
+        run: |
+          shopt -s globstar
+          shopt -s nocaseglob
+          bom_found=false
+          for file in **/*.csv **/*.json **/*.md; do
+            if [ -f "$file" ]; then
+              bom=$(hexdump -n 3 -e '/1 "%02x"' "$file")
+              if [ "$bom" = "efbbbf" ]; then
+                echo "Error: File $file has a BOM"
+                echo "::error file=$file::File has BOM"
+                bom_found=true
+              else
+                echo "File $file is valid"
+              fi
+            fi
+          done
+          if [ "$bom_found" = true ] ; then
+            echo "At least one file has BOM, failing the action"
+            exit 1
           fi
-        fi
-      done
-      if [ "$bom_found" = true ] ; then
-        echo "At least one file has BOM, failing the action"
-        exit 1
-      fi
       
